{{- if .Values.cloudwatch.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-stage-config
  namespace: default
data:
  stage_config: |
    {
      "stageName": "prod",
      "xrayTracingEnabled": true,
      "accessLogSettings": {
        "destinationArn": "arn:aws:logs:{{ .Values.region }}:123456789012:log-group:{{ .Values.cloudwatch.logGroupName }}",
        "format": "{\"requestId\":\"$context.requestId\",\"ip\":\"$context.identity.sourceIp\",\"caller\":\"$context.identity.caller\",\"user\":\"$context.identity.user\",\"requestTime\":\"$context.requestTime\",\"httpMethod\":\"$context.httpMethod\",\"resourcePath\":\"$context.resourcePath\",\"status\":\"$context.status\",\"protocol\":\"$context.protocol\",\"responseLength\":\"$context.responseLength\"}"
      }
    }
{{- end }}
