{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hello-world.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"  # Ensure HTTP to HTTPS redirection
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"  # Use HTTPS protocol
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}  # Your domain or hostname
    secretName: {{ .Values.ingress.tlsSecretName }}  # Name of the TLS secret for HTTPS
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "hello-world.fullname" . }}
            port:
              number: 3000

 ###kubectl create secret tls my-tls-secret --cert=path/to/cert.crt --key=path/to/cert.key
#helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
#helm repo update
#
#helm install ingress-nginx ingress-nginx/ingress-nginx \
#  --set controller.publishService.enabled=true \
#  --set controller.service.type=LoadBalancer
