name: CI Pipeline

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r lambdas/requirements.txt

    - name: Build Lambda zip for Telemetry Processor
      run: |
        cd lambdas
        zip -r telemetry_processor.zip telementary_processor_sqs_postgress_psg.py
      working-directory: ./lambdas

    - name: Build Lambda zip for Acknowledgment Handler
      run: |
        cd lambdas
        zip -r acknowledgment_handler.zip acknoledgement.py
      working-directory: ./lambdas

    - name: Run tests
      run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.10

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform (only if .zip files changed)
      run: |
        terraform plan -out=tfplan
        terraform apply -auto-approve tfplan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
